version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    versioning-strategy: increase
